// <auto-generated />
using System;
using FIIsAnalyzer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FIIsAnalyzer.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("FIIsAnalyzer.Models.Dividendo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Data")
                        .HasColumnType("TEXT");

                    b.Property<int>("FIIId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Valor")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FIIId");

                    b.ToTable("Dividendos");
                });

            modelBuilder.Entity("FIIsAnalyzer.Models.FII", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CotacaoAtual")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantidade")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Setor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("FIIs");
                });

            modelBuilder.Entity("FIIsAnalyzer.Models.HistoricoCotacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Cotacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataReferencia")
                        .HasColumnType("TEXT");

                    b.Property<int>("FiiId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantidade")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FiiId");

                    b.ToTable("HistoricoCotacoes");
                });

            modelBuilder.Entity("FIIsAnalyzer.Models.Dividendo", b =>
                {
                    b.HasOne("FIIsAnalyzer.Models.FII", "FII")
                        .WithMany()
                        .HasForeignKey("FIIId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FII");
                });

            modelBuilder.Entity("FIIsAnalyzer.Models.HistoricoCotacao", b =>
                {
                    b.HasOne("FIIsAnalyzer.Models.FII", "Fii")
                        .WithMany()
                        .HasForeignKey("FiiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fii");
                });
#pragma warning restore 612, 618
        }
    }
}
